### ISSUE TITLE
Failed to update gateway

### ISSUE THREAD

**Issue by r34son** [yc-actions/yc-api-gateway-deploy#381]
<img width="440" alt="image" src="https://github.com/yc-actions/yc-api-gateway-deploy/assets/43549299/6effef6b-1668-45b2-8d94-d30074f20b85">

'yc-actions/yc-api-gateway-deploy@v2' (SHA:e78484635add59f00747afa4efb0c8381e72834e)

Хотя в консоли облака появляется запись operation_update

**Comment by r34son** [comment]
<img width="489" alt="image" src="https://github.com/yc-actions/yc-api-gateway-deploy/assets/43549299/ef2ac679-e321-4eb7-a20e-77a153b0f8bc">

С созданием такая же проблема

**Comment by r34son** [comment]
1 версия работает
<img width="1138" alt="image" src="https://github.com/yc-actions/yc-api-gateway-deploy/assets/43549299/897e5d2a-ed5f-4e0e-b1c2-f21efc87e62f">

**Comment by nikolaymatrosov** [comment]
Версия v2.1.1 должна все исправить

**Comment by r34son** [comment]
Пофиксило, спасибо!
